#!/bin/bash

"$2/JupyterLab.app/Contents/Resources/env_installer/JupyterLabDesktopAppServer-3.2.1-2-MacOSX-x86_64.sh" -b -p "$2/JupyterLab.app/Contents/Resources/jlab_server"

ln -s "$2/JupyterLab.app/Contents/Resources/app/jlab" /usr/local/bin/jlab
chmod 755 "$2/JupyterLab.app/Contents/Resources/app/jlab"

# INSTALL Jupyter JULIA KERNEL manually
## 1) kernel files
cp -R "$2/JupyterLab.app/Contents/Resources/jlab_server-dist/share/jupyter/kernels/julia" "$2/JupyterLab.app/Contents/Resources/jlab_server/share/jupyter/kernels/"
## 2) julia depot ...
mkdir "$2/JupyterLab.app/Contents/Resources/jlab_server/julia"
cp -R "$2/JupyterLab.app/Contents/Resources/jlab_server-dist/julia/depot" "$2/JupyterLab.app/Contents/Resources/jlab_server/julia"
## 3) we had to remove the '-1.6' for julia (constructor was not copying the extraResources)... let's put it back
# THIS IS IMPORTANT: otherwise SoS-julia won't bind to IJulia (cf. %use showing "unavailable" language module)
# or you set supported_kernels = {'Julia': ['julia-?.?','julia']} ~line 208 of site-packages/sos-julia/kernel.py
mv "$2/JupyterLab.app/Contents/Resources/jlab_server/share/jupyter/kernels/julia" "$2/JupyterLab.app/Contents/Resources/jlab_server/share/jupyter/kernels/julia-1.6"

## add in fix for Julia Matrix handling
cp "$2/JupyterLab.app/Contents/Resources/jlab_server-dist/lib/python3.8/site-packages/sos_julia/kernel.py" "$2/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages/sos_julia"

# INSTALL Jupyter STATA KERNEL manually and handles STATA binding
# cp -R "$2/JupyterLab.app/Contents/Resources/jlab_server-dist/share/jupyter/kernels/stata" "$2/JupyterLab.app/Contents/Resources/jlab_server/share/jupyter/kernels/"
# let's just use the normal command line to handle auto-configuration (this will add the kernel in ~/Library/Jupyter/kernels)
"$2/JupyterLab.app/Contents/Resources/jlab_server/bin/python" -m stata_kernel.install --prefix "$2/JupyterLab.app/Contents/Resources/jlab_server"


cp "$2/JupyterLab.app/Contents/Resources/jlab_server-dist/share/jupyter/kernels/sos/kernel.json" "$2/JupyterLab.app/Contents/Resources/jlab_server/share/jupyter/kernels/sos"

# SETUP ENV variables ? (not working)
mkdir -p "$2/JupyterLab.app/Contents/Resources/jlab_server/etc/conda/activate.d"
mkdir -p "$2/JupyterLab.app/Contents/Resources/jlab_server/etc/conda/deactivate.d"
echo -e "#!/bin/sh\n\nexport JULIA_DEPOT_PATH='~/Applications/JupyterLab.app/Contents/Resources/jlab_server/julia/depot'" > "$2/JupyterLab.app/Contents/Resources/jlab_server/etc/conda/activate.d/env_vars.sh"
echo -e "#!/bin/sh\n\nunset JULIA_DEPOT_PATH" > "$2/JupyterLab.app/Contents/Resources/jlab_server/etc/conda/deactivate.d/env_vars.sh"

exit 0